language: node_js
node_js:
  - "4.0"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - npm i -g babel-cli
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i
script:
  - npm run build
  - npm test
